### ISSUE TITLE
The model gives doc synopsis rather than straight OCR result

### ISSUE THREAD

**Issue by zx9088** [imanoop7/Ollama-OCR#3]
is there any way to get the exact OCR result?

**Comment by trameshape** [comment]
Same questions, did you have answer?

**Comment by wengzhiwen** [comment]
it looks it only supports english images with llama3.2-vision

I got the same output just like you said. But for english docs, it works fine

**Comment by imanoop7** [comment]
all the use case, I have seen it gives extracted text with llama3.2 Vision model.
pls attach image and extracted text, will check

**Comment by imanoop7** [comment]
Pls open a create a new one, if the issue persist
